---
# Fixes the openshift-marketplace catalog by recreating it from a new image minus rhsso-operator.
# After that, adds a new catalogsource containing the correct rhsso-operator package.
#
# References:
#   https://docs.openshift.com/container-platform/4.11/operators/admin/olm-restricted-networks.html
#   https://docs.openshift.com/container-platform/4.11/operators/admin/olm-managing-custom-catalogs.html
#   https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/cli_tools/opm-cli
#
# Prep Cheat-sheet:
#
# 1. Get rid of rhsso-operator in the do280-catalog:
#
#   - get a list of existing packages in the do280-catalog
#
#       oc port-forward do280-catalog-foobar 50051:50051
#       grpcurl -plaintext localhost:50051 api.Registry/ListPackages > do280-packages.json
#
#   - remove rhsso-operator from do280-operator-catalog and push create a new image
#
#       opm index prune --from-index quay.io/redhattraining/do280-operator-catalog:v4.10 --tag quay.io/rhtuser/do280-catalog-nosso:v4.10 -p $(grep name do280-packages.json | sed 's/^.*name": "//; s/"$//' | grep -v rhsso-operator | tr '\n' ',' | sed 's/,$//')
#
#   - push the new image up (AUTHENTICATION!)
#
#       podman push quay.io/rhtuser/do280-catalog-nosso:v4.10
#
# 2. Get the latest version of rhsso-operator:
#
#   - take the original operator index (latest version) and prune it of everything but rhsso-operator
#
#       opm index prune --from-index registry.redhat.io/redhat/redhat-operator-index:v4.10 --tag quay.io/rhtuser/do280-sso-operator:v4.10 -p rhsso-operator
#
#   - push the image (AUTHENTICATION!)
#
#       podman push quay.io/rhtuser/do280-sso-operator:v4.10
#
# NOTE: quay.io robot account rhtuser+rhsso must have read access to the above two images.
#         (creds in vars/main.yml)
#
# NOTE: Everything up until here has already been done and only needs to be done once.
#
# This is necessary immediately after lab create.
- name: Wait for the marketplace-operator to be up
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: v1
    kind: pod
    namespace: openshift-marketplace
    label_selectors:
      - name=marketplace-operator
  register: mktplc_pod
  until:
    - (mktplc_pod.resources | length) == 1
    - mktplc_pod.resources[0].status.containerStatuses[0].ready
  retries: 30
  delay: 10


- name: Get info about the rhbk-operator
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: packages.operators.coreos.com/v1
    kind: packagemanifest
    namespace: openshift-marketplace
    name: rhbk-operator
  register: rhbk_mft

- name: Ensure the RHBK catalog source is there as well
  k8s:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: operators.coreos.com/v1alpha1
    kind: catalogsource
    namespace: openshift-marketplace
    name: do280-rhbk
    state: present
    definition:
      spec:
        displayName: "do280 RHBK Catalog"
        image: "{{ catalog_rhbk_image }}"
        publisher: "Red Hat"
        sourceType: "grpc"

- name: Wait for the catalogsource to be ready.
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: operators.coreos.com/v1alpha1
    kind: catalogsource
    namespace: openshift-marketplace
    name: do280-rhbk
  register: rhbk_cat
  until:
    - (rhbk_cat.resources | length) == 1
    - rhbk_cat.resources[0].status is defined
    - rhbk_cat.resources[0].status.connectionState.lastObservedState == "READY"
  retries: 30
  delay: 10

- name: Wait for the rhbk-operator packagemanifest to appear.
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: packages.operators.coreos.com/v1
    kind: packagemanifest
    namespace: openshift-marketplace
    name: rhbk-operator
  register: rhbk_mft
  until:
    - (rhbk_mft.resources | length) == 1
    - rhbk_mft.resources[0].status.catalogSource == "do280-rhbk"
    - rhbk_mft.resources[0].status.packageName == "rhbk-operator"
  retries: 30
  delay: 10

- assert:
    that:
      - rhbk_mft.resources is defined
      - (rhbk_mft.resources | length) > 0
      - rhbk_mft.resources[0].status.catalogSource == "do280-rhbk"
      - '"rhbk-operator.v24.0.5-opr.1" in (rhbk_mft.resources[0] | community.general.json_query("status.channels[*].currentCSV") | list)'
    fail_msg: "ERROR: rhbk-operator package manifest not deployed correctly."
    success_msg: "OK: rhbk-operator package manifest configured correctly."
...
