---
# Ensures the RHSSO instance (driven by a KeyCloak resource) is there.
#
- name: Check that the CSV is there and completed
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: operators.coreos.com/v1alpha1
    kind: clusterserviceversion
    namespace: rhbk
    name: rhbk-operator.v26.0.7-opr.1
  register: rhbk_csv

- assert:
    that:
      - rhbk_csv.resources is defined
      - (rhbk_csv.resources | length) == 1
      - rhbk_csv.resources[0].status.phase == "Succeeded"
    fail_msg: "ERROR: RHBK operator not deployed or not registered correctly."
    success_msg: "OK: RHBK operator deployed correctly."

- name: Check for the presence of stray KeyCloak resources
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: k8skeycloak.org/v2alpha1
    kind: keycloak
    namespace: rhbk
  register: rhbk_cr

- assert:
    that:
      - (rhbk_cr.resources | length) == 1
      - rhbk_cr.resources[0].metadata.name == "rhbk"
    fail_msg: "ERROR: RHBK instances other than the required one exist."
    success_msg: "OK: Required RHSSO instance exists."
  when:
    - rhbk_cr.resources is defined
    - (rhbk_cr.resources | length) > 0

- name: Make sure there is a KeyCloak resource in the project
  k8s:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: k8s.keycloak.org/v2alpha1
    kind: keycloak
    namespace: rhbk
    name: rhbk
    definition:
      metadata:
        labels:
          app: rhbk
      spec:
        db:
          database: rhbk
          host: rhbk-db
          passwordSecret:
            key: password
            name: rhbk-db-secret
          port: 5432
          usernameSecret:
            key: username
            name: rhbk-db-secret
          vendor: postgres
        hostname:
          hostname: rhbk-rhbk.apps.ocp4.example.com
        http:
          httpEnabled: false
          tlsSecret: rhbk-tls-secret
        instances: 1

- name: Wait for the KeyCloak resource to show ready state
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: k8s.keycloak.org/v2alpha1
    kind: keycloak
    namespace: rhbk
    name: rhbk
  register: rhbk_cr
  until:
    - (rhbk_cr.resources | length) == 1
    - rhbk_cr.resources[0].status is defined
    - rhbk_cr.resources[0].status.ready
    - rhbk_cr.resources[0].status.phase == "reconciling"
  retries: 30
  delay: 10

- name: Show some basic information about the instance.
  pause:
    prompt: |-
      *******************************************************************************************************
      KeyCloak instance rhbk is now available. You can run `oc get routes -o yaml -o jsonpath='https://{.items[0].status.ingress[0].host}' -n rhbk ` 
      You can obtain the necessary credentials from `oc extract secret/rhbk-initial-admin --to=-`
      *******************************************************************************************************
    seconds: 5
...
