---
# Ensures the RHSSO instance (driven by a KeyCloak resource) is there.
#
- name: Check that the CSV is there and completed
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: operators.coreos.com/v1alpha1
    kind: clusterserviceversion
    namespace: rhbk
    name: rhbk-operator.v26.0.7-opr.1
  register: rhbk_csv

- assert:
    that:
      - rhbk_csv.resources is defined
      - (rhbk_csv.resources | length) == 1
      - rhbk_csv.resources[0].status.phase == "Succeeded"
    fail_msg: "ERROR: RHBK operator not deployed or not registered correctly."
    success_msg: "OK: RHBK operator deployed correctly."

- name: Deploy PostgreSQL 16 server
  k8s:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: apps/v1
    kind: statefulset
    namespace: rhbk
    name: rhbk-db
    definition:
      spec:
        serviceName: rhbk-db-service
        selector:
          matchLabels:
            app: rhbk-db
        replicas: 1
        template:
          metadata:
            labels:
              app: rhbk-db
          spec:
            containers:
              - name: rhbk-db
                image: quay.io/aletiasolucionesit/postgresql-16
                volumeMounts:
                  - mountPath: /var/lib/pgsql/data
                    name: db-data-volume
                env:
                  - name: POSTGRESQL_PASSWORD
                    value: rhbkdbpassword
                  - name: POSTGRESQL_USER
                    value: rhbkdbuser
                  - name: POSTGRESQL_DATABASE
                    value: rhbk
        volumeClaimTemplates:
          - metadata:
              name: db-data-volume
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 5Gi

- name: Deploy PostgreSQL 16 service
  k8s:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: v1
    kind: service
    namespace: rhbk
    name: rhbk-db
    definition:
      spec:
        selector:
          app: rhbk-db
        ports:
        - port: 5432
          targetPort: 5432

- name: Check for the presence of stray KeyCloak resources
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: k8skeycloak.org/v2alpha1
    kind: keycloak
    namespace: rhbk
  register: rhbk_cr

- assert:
    that:
      - (rhbk_cr.resources | length) == 1
      - rhbk_cr.resources[0].metadata.name == "rhbk"
    fail_msg: "ERROR: RHBK instances other than the required one exist."
    success_msg: "OK: Required RHBK instance exists."
  when:
    - rhbk_cr.resources is defined
    - (rhbk_cr.resources | length) > 0

- name: Create database secret
  k8s:
    state: present
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    resource_definition:
      apiVersion: v1
      data:
        password: cmhia2RicGFzc3dvcmQ=
        username: cmhia2RidXNlcg==
      kind: Secret
      metadata:
        name: rhbk-db-secret
        namespace: rhbk
      type: Opaque

- name: Create RHBK Self Signed Certificate
  command: >-
    openssl req -subj '/CN=rhbk-rhbk.apps.ocp4.example.com/O=Red Hat Build of Keycloak./C=US' -addext "subjectAltName = DNS:rhbk-rhbk.apps.ocp4.example.com" -newkey rsa:2048 -nodes -keyout /home/student/rhbk-key.pem -x509 -days 365 -out /home/student/rhbk-cert.pem

- name: Copy RHBK Cert to System Trust
  copy:
    src: /home/student/rhbk-cert.pem
    dest: /etc/pki/ca-trust/source/anchors/rhbk-cert.pem
    remote_src: true
  become: true

- name: Update System Trust
  command: >-
    update-ca-trust
  become: true

- name: Remove TLS secret
  k8s:
    state: absent
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: v1
    kind: secret
    namespace: rhbk
    name: rhbk-tls-secret

- name: Create TLS secret
  k8s:
    state: present
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    resource_definition:
      apiVersion: v1
      data:
        tls.crt: "{{ lookup('file', '/home/student/rhbk-cert.pem') | b64encode }}"
        tls.key: "{{ lookup('file', '/home/student/rhbk-key.pem') | b64encode }}"
      kind: Secret
      metadata:
        name: rhbk-tls-secret
        namespace: rhbk
      type: kubernetes.io/tls
    
- name: Make sure there is a KeyCloak resource in the project
  k8s:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: k8s.keycloak.org/v2alpha1
    kind: keycloak
    namespace: rhbk
    name: rhbk
    definition:
      metadata:
        labels:
          app: rhbk
      spec:
        db:
          database: rhbk
          host: rhbk-db
          passwordSecret:
            key: password
            name: rhbk-db-secret
          port: 5432
          usernameSecret:
            key: username
            name: rhbk-db-secret
          vendor: postgres
        hostname:
          hostname: rhbk-rhbk.apps.ocp4.example.com
        http:
          httpEnabled: false
          tlsSecret: rhbk-tls-secret
        instances: 1

- name: Wait for the KeyCloak resource to show ready state
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: k8s.keycloak.org/v2alpha1
    kind: keycloak
    namespace: rhbk
    name: rhbk
  register: rhbk_cr
  until:
    - (rhbk_cr.resources | length) == 1
    - rhbk_cr.resources[0].status is defined
    - rhbk_cr.resources[0].status | json_query('conditions[?type==`Ready` && status==`True`].status')
  retries: 30
  delay: 10

- name: Show some basic information about the instance.
  pause:
    prompt: |-
      *******************************************************************************************************
      KeyCloak instance rhbk is now available. You can run `oc get routes -o yaml -o jsonpath='https://{.items[0].status.ingress[0].host}' -n rhbk ` 
      You can obtain the necessary credentials from `oc extract secret/rhbk-initial-admin --to=-`
      *******************************************************************************************************
    seconds: 5
...
