---
# need the following variables somewhere in global vars collection:
# 
#  - tools
#  - clusters
#  - need_sso_zip
#  - need_sso_patch
#  - need_sso_hotfix
#
# consult the role tasks file for an explanation
rhbk_n: 26.0.7
rhbk_p: 24.0.5
standalone: false
...
