---
# The users this role will create, along with their group memberships:
pop_users:
  - username: admindemo
    password: redhat123
    firstname: Admin
    lastname: Demo
    isadmin: true
  - username: userdemo
    password: redhat123
    firstname: User
    lastname: Demo
    isadmin: false

oidc_client_id: openid-demo-client
valid_redirect_uris: "http://secureapi.apps.ocp4.example.com/api/*"
