---
# Ensures that there are also users, groups, and roles in the test realm.
- name: Check for the KeyCloak resource
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: k8s.keycloak.org/v2alpha1
    kind: keycloak
    namespace: rhbk
    name: rhbk
  register: rhbk_cr

- assert:
    that:
      - (rhbk_cr.resources | length) == 1
      - rhbk_cr.resources[0].status.ready
      - rhbk_cr.resources[0].status.phase == "reconciling"
    fail_msg: "ERROR: RHBK instance is missing or not configured correctly."
    success_msg: "OK: RHBK instance is configured correctly."

- name: Store RHBK URL as a fact
  set_fact:
    rhbk_url: "https://rhbk-rhbk.apps.ocp4.example.com"

# Authentication bits from here until we can get group list.
- name: Read the RHBK admin user and password
  k8s_info:
    kubeconfig: tmp/kubeconfig-ocp4
    validate_certs: no
    api_version: v1
    kind: secret
    namespace: rhbk
    name: "rhbk-initial-admin"
  register: rhbk_secret

- name: Store RHBK admin user as fact
  set_fact:
    rhbk_admin: "{{ rhbk_secret.resources[0].data.username }}"

- name: Store RHBK admin pass as fact
  set_fact:
    rhbk_pass: "{{ rhbk_secret.resources[0].data.password }}"

- name: Get an auth token from RHSSO
  uri:
    method: POST
    return_content: true
    validate_certs: false
    url: "{{ rhbk_url }}/realms/master/protocol/openid-connect/token"
    headers:
      Accept: application/json
    body: "client_id=admin-cli&username={{ rhbk_admin | string | b64decode }}&password={{ rhbk_pass | string | b64decode }}&grant_type=password"
  register: rhbk_token_rsp

- assert:
    that: rhbk_token_rsp.json is defined and sso_token_rsp.json.access_token is defined
    fail_msg: "ERROR: Failed to obtain authentication token from RHBK."
    success_msg: "OK: got authentication token."

- name: Store the token as a fact
  set_fact:
    rhbk_token: "{{ rhbk_token_rsp.json.access_token }}"

# Back to business as usual from here on.
- name: Create sample realm
  uri:
    method: POST
    return_content: true
    validate_certs: false
    url: "{{ rhbk_url}}/admin/realms"
    headers:
      Authorization: Bearer {{ rhbk_token }}
      Accept: application/json
      Content-Type: application/json
    body_format: json
    body: >-
      {"realm": "sample", "enabled": true}
    status_code:
      - 200
      - 201
      - 204

- name: Get existing group list
  uri:
    method: GET
    return_content: true
    validate_certs: false
    url: "{{ rhbk_url }}/admin/realms/sample/groups"
    headers:
      Authorization: Bearer {{ rhbk_token }}
      Accept: application/json
  register: rhbk_groups_raw
  tags:
    - groups

- name: Store existing groups as a list
  set_fact:
    rhbk_groups: "{{ rhbk_groups_raw.json | items2dict(key_name='name', value_name='id') }}"
  tags:
    - groups

- name: Create missing groups
  uri:
    method: POST
    return_content: true
    validate_certs: false
    url: "{{ rhbk_url }}/admin/realms/sample/groups"
    headers:
      Authorization: Bearer {{ rhbk_token }}
      Accept: application/json
      Content-Type: application/json
    body_format: json
    body: '{"name": "{{ item | string }}"}'
    status_code:
      - 200
      - 201
      - 204
  loop: "{{ pop_groups }}"
  when: item not in rhbk_groups.keys()
  tags:
    - groups
# You need offline_access in realmRoles to be able to use OCP OIDC.
- name: Make sure KeycloakUser resources exist
  uri:
    method: POST
    return_content: true
    validate_certs: false
    url: "{{ rhbk_url }}/admin/realms/sample/groups"
    headers:
      Authorization: Bearer {{ rhbk_token }}
      Accept: application/json
      Content-Type: application/json
    body_format: json
    body: >-
      {"firstName": {{ item.firstname }} ,"lastName": {{ item.lastname }} , "username": {{ item.username }},"email": {{ item.username }}"@example.com", "enabled": "true", "credentials":[{"type":"password","value": {{ item.password }},"temporary":false}], "emailVerified": "true", "groups": {{ item.groups | list }}, "realmRoles": ["offline_access"]}
  loop: "{{ pop_users }}"
  tags:
    - users
